### ISSUE TITLE
[Question] Notepad++ plugin compatibility

### ISSUE THREAD

**Issue by pidgeon777** [dail8859/NotepadNext#11]
Hello, congratulations on this interesting project.

Is it compatible with Notepad++ plugins, and if not is there any plan to support them in the future?

Thank you

**Comment by dail8859** [comment]
Hello.

It is not compatible with Notepad++ plugins and would honestly say it would be near impossible to support them and guarantee ABI compatibility. Some things in theory could be supported (the message and notifications) but if the plugin did something Windows specific (hooking keyboard input, message queues, etc) then I have no clue what would happen since Notepad Next is built in Qt which abstracts all the OS specifics away.

At this early stage in the project I've not really given any thought to external plugin support just because the core of the code is in a state of flux.
