### ISSUE TITLE
HiDPI QT workaround in Windows

### ISSUE THREAD

**Issue by FadeMind** [dail8859/NotepadNext#112]
**NotepadNext.cmd**
```
:: NotepadNext.cmd :

set QT_SCALE_FACTOR=0
set QT_AUTO_SCREEN_SCALE_FACTOR=0
set "QT_SCREEN_SCALE_FACTORS=DISPLAY2=1;DISPLAY1=1"

start "" "NotepadNext.exe"
```

NORMAL
![20220420-1650462018](https://user-images.githubusercontent.com/9846948/164243726-825deee0-bfb1-4d65-b06e-4f9d13fc74ed.png)

FIX FROM CMD
![20220420-1650462042](https://user-images.githubusercontent.com/9846948/164243807-db85514b-64a8-41af-baae-1e1c71470566.png)

**Comment by dail8859** [comment]
@FadeMind 

Thanks for info! My understanding is Qt6 handles scaling differently vs Qt5.

If you get a chance try this Qt6 snapshot build to see if the behavior is any better for you without the need for environment varaibles? I'll have to read up on High DPI in Qt.

https://github.com/dail8859/NotepadNext/suites/6189635741/artifacts/217956067

I'll have to read up on high DPI in Qt because I thought this was suppose to make high DPI scaling work...guess not.

https://github.com/dail8859/NotepadNext/blob/3477b35e484376c0bfa3331c7f8d1dc5305b39b5/src/NotepadNext/main.cpp#L41-L44

**Comment by FadeMind** [comment]
@dail8859 I have 2K display here with 150% scalling (default)
![20220420-1650478259](https://user-images.githubusercontent.com/9846948/164295393-15a4a993-26c3-4564-8373-741d214346ed.png)
