### ISSUE TITLE
Suggestion: Specify roadmap

### ISSUE THREAD

**Issue by dzek69** [dail8859/NotepadNext#127]
I'd be cool to have a roadmap, so people knows what to expect, when their beloved feature of N++ will be implemented into Next or even for developers wanting to help to know what to focus on.

I'm not asking for dates, more like ordered milestones. Just to have an overview that may of course change.

Good luck with the project. I may use it in the future after I will ditch Win10 again for Linux :)

**Comment by dail8859** [comment]
FYI I haven't been ignoring this. I've been trying to put some thought into some sort of roadmap but it's actually kinda difficult since this entire project was meant for myself to learn Qt and have some fun.

That being said it's nice that others are interested in the project so having some basic overview/roadmap/design plan would help others get involved.

So I'll try to find some time and get something together and share it.

**Comment by dzek69** [comment]
@dail8859 I see this closed as completed, where can I find the roadmap? I can't see it anywhere.

I don't want to be a pain in the ass, I know this is a hobby project, just asking if I missed something or maybe there is a git push to come :)

**Comment by dzek69** [comment]
That's totally valid, maybe it is a good idea to describe it loud and clear in README?
