### ISSUE TITLE
Suggestion: Add to homebrew

### ISSUE THREAD

**Issue by Austin1** [dail8859/NotepadNext#138]
Make NotepadNext installable via brew - https://docs.brew.sh/Formula-Cookbook

**Comment by dail8859** [comment]
@Austin1 Thanks for the suggestion.

I've already been quite cautious about the various distribution methods as this can quickly become unmanageable and makes creating new releases burdensome (it's already a bit tedious and trying to improve that).

Part of the issue is I have no experience when it comes to the MacOS environment and have no ways to test/debug/troubleshoot any kind of MacOS issues. I am also not familiar with homebrew at all so I don't know what level of effort is involved. The dmg available was kind of an 'easy' way to get it on MacOS initially to see what kind of interest there was.

So my current stance is that I won't be supporting homebrew distribution myself. If someone wants to 'unofficially' support this that's fine. Maybe at a later date if homebrew seems to be worth the time vs effort then this project can officially support it.

That being said if there are specific, small changes that need done to the project to support homebrew that's fine as long as they don't have any impact to the rest of the build system, etc. Large structural application changes won't be made just for homebrew.
