### ISSUE TITLE
Windows environment variable conflict

### ISSUE THREAD

**Issue by nautiluschan** [dail8859/NotepadNext#151]
Windows 7
I got an error message when I first time run NotepadNext : This application failed to start because not Qt platform plugin could be initialized.Reinstalling the application may fix this problem.
I found the environment variable "QT_PLUGIN_PATH" had been used by another application. So I suggest NotepadNext using a non-common  environment variable name.

**Comment by dail8859** [comment]
[QT_PLUGIN_PATH](https://doc.qt.io/qt-5/deployment-plugins.html#the-plugin-directory) is for configuring the Qt Framework that this application uses.

Notepad Next does not set/create/modify the QT_PLUGIN_PATH environment variable at all.

Some other application set this environment variable on your system. The Qt documentation linked above even specifies: 

> Note: Do not export QT_PLUGIN_PATH as a system-wide environment variable because it can interfere with other Qt installations.

Because it can lead to errors exactly like the one you ran into. So there's nothing Notepad Next can do about this since technically it is expected behavior.
