### ISSUE TITLE
On Windows, very basic bug: memory leak

### ISSUE THREAD

**Issue by kgfly** [dail8859/NotepadNext#170]
Test case:
Open a big exe, such as Skype-8.85.0.409.exe, 86MB

Observed:
Memory consumption: 348 MB.

Close the file and open again.

Observed:
Memory consumption: 645 MB.

Do it 3rd time. MEM: about 1GB.

Issue: memory is not freed when closing the file.

Thanks.

**Comment by dail8859** [comment]
Note to self:

I've tracked down the issue to usage of this function:

https://github.com/dail8859/NotepadNext/blob/672b77aabd3f7ec6d57e6ba90f34f6199f5fc183/src/scintilla/qt/ScintillaEdit/ScintillaEdit.cpp#L53-L55

The `new`ed `ScintillaDocument` is adding a reference to the document pointer that gets passed in. Since the returned `ScintillaDocument` pointer is not getting deleted in a couple places (EditorInfoStatusBar, LanguageInspectorDock) then the document is not being released since it still has references.

The reason to use `get_doc()` is to connect to the `ScintillaDocument::lexer_changed()` signal.
