### ISSUE TITLE
Compare files

### ISSUE THREAD

**Issue by Anuskuss** [dail8859/NotepadNext#173]
The most important feature for me is the ability to compare two files.

**Comment by dail8859** [comment]
Notepad++ is only able to compare files via a plugin, and even that has had a ton of development work. I don't have any plans to natively support this functionality, but that doesn't mean it would _never_ happen. If someone else took an interest in this and developed a clean implementation I'd be willing to accepting a PR for this functionality. I'll close this for now since most likely this functionality won't show up for a long time.

**Comment by Anuskuss** [comment]
Plugin support would be dreams but probably not happening in the near future. But that doesn't mean that you couldn't write your own solution, right? Anyway, it's clear that you don't want to work on this (currently), which is fine.

Anyone coming from Google: [Sublime Text](https://www.sublimetext.com) is a decent alternative and has a plugin called [Compare Side-By-Side](https://packagecontrol.io/packages/Compare%20Side-By-Side).

**Comment by dail8859** [comment]
> But that doesn't mean that you couldn't write your own solution, right?

Correct. There is still alot of "core" functionality that is missing and needs improvement. If this application was more feature-equivalent with Notepad++ then yes I'd agree native file compare functionality would be worth attempting.

**Comment by Leoncl2025** [comment]
Compare is supported in https://github.com/Leoncl2025/NotepadSharp
