### ISSUE TITLE
On update, NotepadNext didn't close

### ISSUE THREAD

**Issue by Nim** [dail8859/NotepadNext#211]
When doing in-app update, there is a big screen to confirm that NotepadNext need to be closed before update.
But app didn't close, and Updater shows error (Retry, Ignore, Cancel).
After manually closing app, and pressing Retry button, update continues normally.

**Comment by dail8859** [comment]
Just recently there was a feature added for the installer to auto-detect if the application is running (rather than showing an error message) and ask the user to close it. It was never intended to force-close the application. Maybe some day when Notepad Next supports saving/loading a user session then that functionality could be re-evaluated.

You would not have seen this when upgrading from v0.5.4 to v0.5.5. If you rerun the v0.5.5 installer it will detect if it is running and ask you to close it.

78d19cf6f149f493251e3b6134a5ff89b0652e61
