### ISSUE TITLE
[Feature request] shortcut support for duplicate current line or selected lines

### ISSUE THREAD

**Issue by wwxyz001** [dail8859/NotepadNext#245]
shortcut support for duplicate current line or selected lines. On notepad++ this shortcut is CTRL+D.

**Comment by dail8859** [comment]
You can duplicate the current line with `Edit > Line Operations > Duplicate Current Line`. There's no shortcut key associated with it. 

For now I'm fine leaving `Ctrl+D` to select the next instance of a selected word, due to the fact many other editors do it this way. Hopefully there will be support to modify shortcut keys in the future
