### ISSUE TITLE
UI scale is off

### ISSUE THREAD

**Issue by savchenko** [dail8859/NotepadNext#277]
Windows 10 21H2
Notepad Next v0.5.6

Note the UI font size in comparison to GitHub opened in the web-browser and Windows settings application:

 ![image](https://user-images.githubusercontent.com/300146/203215594-e8018bc5-1fce-42f5-82a1-7d5b6cbb6ab7.png)

**Comment by dail8859** [comment]
See #112 and #226 about UI scaling which sounds very similar. (maybe there is something there that will help)

If you have a chance you can try this stand alone Qt6 version, which my understanding is Qt6 handles UI scaling differently. Its the same as v0.5.6 but bundle Qt6 instead of Qt5. Just unzip it and run it, it won't mess with your current install

https://github.com/dail8859/NotepadNext/suites/9409932643/artifacts/444277500

**Comment by dail8859** [comment]
> Probably unsurprising given that link leads to NotepadNext-Windows-Qt5.15.2-Zip.zip?

Sorry about that. Here's the Qt6 version: https://github.com/dail8859/NotepadNext/suites/9409932643/artifacts/444277501
