### ISSUE TITLE
VCRUNTIME140_1.DLL is missing from your computer

### ISSUE THREAD

**Issue by Nothoro** [dail8859/NotepadNext#286]
"The program can't start because VCRUNTIME140_1.DLL is missing from your computer."
Which runtime must I install to use this? Why wasn't it included in a redist folder?

**Comment by dail8859** [comment]
> Which runtime must I install to use this? 

I'm honestly not 100% sure. I believe the x64 [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) should be sufficient.

> Why wasn't it included in a redist folder?

Many applications assume the redistributable is already installed. Packaging an extra 20MB+ doesn't really seem worth it since the majority of users will already have this installed.

**Comment by ZachBacon** [comment]
Sorry to comment on an already closed topic, but for future released, you should at least include the redist, or better solution, just have the installer open the browser to the specific runtime that's used.

**Comment by dail8859** [comment]
I'd hate to inflate the installer for a situation that doesn't happen often. Opening a browser or popping up a notification is probably the best option.

I'm curious how other applications handle the situation since I'd guess this problem isn't unique to this application.

**Comment by ZachBacon** [comment]
I've seen some applications link to the runtime by opening the browser. I did something similar using nsis, but you're not using nsis are you? I don't recall. Half the time I use Linux, so most of my knowledge is coming from the days I used to use windows.

**Comment by dail8859** [comment]
I am using nsis: https://github.com/dail8859/NotepadNext/blob/master/installer/installer.nsi

**Comment by dail8859** [comment]
Noting this down to look at later when I get some time: https://github.com/GitCommons/cpp-redist-nsis

**Comment by dail8859** [comment]
I tried to use this: https://github.com/RedisInsight/RedisDesktopManager/blob/15f6d85528cdb957f09ace0ee5cdf8df0640954c/build/windows/installer/include/install_vcredist_x64.nsh

I uninstalled the 2015-2022 runtime on my PC but it still somehow detects it as being installed. If someone is interested in giving it a try on a different PC I can create a pull request to build an installer to test with.

I really want to make sure the change is accurate because I'd hate to push out an installer that tries to errantly install the runtime on many users' PCs.
