### ISSUE TITLE
replace couldn't replace all match text

### ISSUE THREAD

**Issue by webb2016** [dail8859/NotepadNext#292]
I have a file like this. I want to replace "en" to anothor word. Search "en" can hit all the matches, but use "replace" can only hit part of matches. 
Search "en" 22 hits in 1 files. Replace 13 matches.
Mac OS    Notepad Next v0.5.6

File:
2000: {"en": 
2001: {"en": 
2002: {"en": 
2003: {"en": 
2004: {"en": 
2005: {"en": 
2006: {"en": 
2007: {"en": 
2008: {"en": 
2009: {"en": 

2100: {"en": 
2101: {"en": 
2102: {"en": 
2103: {"en": 
2104: {"en": 
2105: {"en": 
2106: {"en": 
2107: {"en": 
2108: {"en": 
2109: {"en": 
2110: {"en": 
2111: {"en":

**Comment by dail8859** [comment]
@webb2016 Thanks for opening the issue!

Looks like when the text being replaced is larger than the text found it is causing the document to grow as expected, but the "replace all" functionality is still limiting the search area to the original size.

I believe this line: 

https://github.com/dail8859/NotepadNext/blob/5c4bc23dc2d4916abff02cc1a8e3d195e8b7e87d/src/NotepadNext/ScintillaNext.h#L51

Needs changed to something like:

```cpp
void forEachMatch(const QByteArray &byteArray, Func callback) { forEachMatchInRange(byteArray, callback, {0, -1}); }
```

I'll have to do some testing later since I'm not on my development machine currently.
