### ISSUE TITLE
Bug when switching languages

### ISSUE THREAD

**Issue by guy038** [dail8859/NotepadNext#310]
Hi, **Justin Dailey**  and the **Team**,

Congratulations for this new **Notepad++ cross-platform** development ;-))

I've just tried the **`NotepadNext-v0.6-win64.zip`** archive and, as soon as I extracted all the stuff, I ran **NotepadNext** without any problem !

I understand that you're just at the **beginning** of the story...

One **bug** :

When you open a **text** file and then choose a **language** for this file, even if you click again for **`language = Text`**, you don't get the **`Normal Text`** syntax. You need to close the **text** file  ( **`Ctrl + W`** ) and **re-open** it with **`Ctrl + Shift + T`** to get the correct **`Text`**  language

Good luck for this **promising** implementation !

Best Regards

guy038 ( **Windows** N++ user )

**Comment by inkydragon** [comment]
I can confirm this issue on win64 with npn v0.6.

Reproduction steps:
1. Create a new empty file
2. Paste some C++ code. No highlighting at this point
3. Select the language as `C++`. Now the code is highlighted
4. Select the language as `text`. the highlighting does not disappear (bug)

**Comment by PaddyTB** [comment]
I can conform the same behaviour on macOS.

I note that switching between languages appears apply the selected syntax highlighting for all languages except TXT - is this because TXT is an absence of syntax high-lighting rather than a style in its own right?

If I open for example a JSON file (with ext .json) then change the language to TXT it still doesn't remove the highlighting, but if I then reload the file using the Reload from the File menu it does remove the highlighting...

HTH

**Comment by dail8859** [comment]
Hello @guy038 and all! Thanks for the issue and steps to reproduce this so easily.

> is this because TXT is an absence of syntax high-lighting rather than a style in its own right?

Kind of. Technically it sets everything to a single style. For some reason though it is not reprocessing the document and the old styling information is still applied. Will need to look into this more to see if it is a Scintilla bug or if Notepad++ does something specific.

**Comment by dail8859** [comment]
So looks like there was a 2-fold issue. One issue is that setting a new lexer isn't guaranteed to remove the previous styling information. Not sure the exact reasons for this but since the "null" lexer tries to shortcut the lexing process it just keeps the previous styling information. Secondly since the "Text" language itself didn't define any style definitions (color, italics, etc) it just used whatever was in style 0.

I've got a fix for this I'll test a bit more and push soon<sup>tm</sup>
