### ISSUE TITLE
Suggest a new icon

### ISSUE THREAD

**Issue by timnick-snow** [dail8859/NotepadNext#311]
![image](https://user-images.githubusercontent.com/33312542/215632737-f09af4de-374d-4c72-9464-3ea5229ba2b1.png)

The icon used now is the icon of the new file, which does not show very well that this is notepadNext.
Sometimes I often can't find where notepadNext is, because it is difficult to associate the new icon with notepadNext

**Comment by elcuco** [comment]
the link at the end of the "About" is also borked...

**Comment by dail8859** [comment]
I'm definitely not a graphics designer, so if you have some concrete examples I'd be willing to take a look. The icon was just something quick I put together a long time ago.

> Sometimes I often can't find where notepadNext is, because it is difficult to associate the new icon with notepadNext

Not sure I understand. You mean like in the taskbar? or somewhere else?

> the link at the end of the "About" is also borked...

Yeah, the text is just a verbatim copy of the GPL header and never thought twice about it until you mentioned it just now.

**Comment by timnick-snow** [comment]
> Not sure I understand. You mean like in the taskbar? or somewhere else?
yes, in the taskbar. When I opened many applications, I could not easily find notepadNext, because of the confusing nature of its icon

**Comment by dail8859** [comment]
@timnick-snow Can you provide a screenshot?

It looks fine to me. Just another icon.

![image](https://user-images.githubusercontent.com/3694843/215917150-d13ddeff-e4ad-4358-9bea-9517d0771232.png)

What specifically makes it hard to find?

**Comment by timnick-snow** [comment]
> @timnick-snow Can you provide a screenshot?
> 
> It looks fine to me. Just another icon.
> 
> ![image](https://user-images.githubusercontent.com/3694843/215917150-d13ddeff-e4ad-4358-9bea-9517d0771232.png)
> 
> What specifically makes it hard to find?

![image](https://user-images.githubusercontent.com/33312542/215991851-0ad307ed-a465-44ee-9419-b1f3d2218f88.png)

This may be my problem. Since the icon now gives me the first impression of creating or adding something, I may not be so sensitive to realize that it is notepadNext

**Comment by PaddyTB** [comment]
I guess the '+' symbol is making the OP think 'New document'? Personally happy with the icon tho' always open to change if there's an icon expert out there with some free time!

**Comment by dail8859** [comment]
> Personally happy with the icon tho' always open to change if there's an icon expert out there with some free time!

This is my thought as well. If there is someone willing to mockup some ideas or make concrete suggestions/alternatives, I'm definitely willing to consider other options. For now though I'll stick with the current icon.

**Comment by ADTC** [comment]
@dail8859 In macOS, the icon looks out of place. Most macOS apps, even those from third parties including Microsoft, have a design language that emphasizes on the "soft rounded square" aesthetic.

<img width="872" alt="Image" src="https://github.com/user-attachments/assets/cfd467d2-bc98-4e25-8bab-0fcdd39633e7" />

---
While the icon works well in Windows taskbar, it stands out on the macOS Dock as an oddball with its more rectangular style with sharper corners.

Even just scaling down the current icon and placing it inside a gray square, like the Calculator icon, would vastly improve the aesthetic. (I believe there must be a way to have different icons for different platforms so that you won't see that in Windows.)

I'm choosing to post this here, instead of opening another issue that may just be closed as 'not planned', same as #704 and #774.

PS: Yes, Spotify icon is a circle, and Trash icon is, well, trash. Though if you notice all app icons look like perfectly aligned squares (including Spotify which fits within that square), except for NotepadNext icon which sticks out more at the top and bottom.

**Comment by dail8859** [comment]
@ADTC Appreciate the screenshot and feedback. At this point there probably wont be a complete revamp of the icon, however if there's way to make the existing icon fit in a bit better on the macOS dock then I'd be fine if someone wanted to improve that (e.g. like what you suggested by just sticking it in a gray rounded square). And to be honest I'm not even 100% sure which icon in the repository even controls that part...I'm assuming it is https://github.com/dail8859/NotepadNext/blob/master/icon/NotepadNext.icns but someone on a mac would need to play around with it and test it out.

**Comment by ADTC** [comment]
Hey, yes it's probably that one. ICNS is known to be Apple's version of Microsoft's ICO format. Let me see what I can do.
