### ISSUE TITLE
Program crashes when opening files without permissions

### ISSUE THREAD

**Issue by timnick-snow** [dail8859/NotepadNext#321]

**Comment by dail8859** [comment]
Could you provide specific details and a set of specific steps?

Do you not have read access to the file?

**Comment by timnick-snow** [comment]
win11
I don't seem to have read access to this file
![image](https://user-images.githubusercontent.com/33312542/217130295-a399e250-27ba-4d83-a856-b283995e4cd0.png)

I don't know the permissions of this file when I wish to open it, but notepadnext should not crash

**Comment by dail8859** [comment]
> but notepadnext should not crash

I agree, but if I can't reproduce the issue I can't fix it. I'm not sure exactly what's special about that file.

**Comment by inkydragon** [comment]
I can reproduce the problem.

1. Create a new text file
2. Modify his permissions to set Deny `Read`, Deny `Read and Execute` for the current user  
	The account I tested is the admin. I disabled permissions for `Users` group.
4. Open the file using npn
5. npn crashed

**Comment by dail8859** [comment]
@inkydragon Thanks! I'm not at my development machine currently but looking from the logs you provided it looks like this line is returning a null pointer due to the error

https://github.com/dail8859/NotepadNext/blob/ada1cf98af9f4be37c002c70501a8ade59ee6365/src/NotepadNext/ScintillaNext.cpp#L94

And then the first thing that pointer is used for is to clear a command key:

https://github.com/dail8859/NotepadNext/blob/ee8021ff33c916d07dccabbbff67c54df0693177/src/NotepadNext/EditorManager.cpp#L108

All comes down to properly handling error cases since that was not thoroughly tested when I wrote parts of the code.

**Comment by dail8859** [comment]
Just FYI It looks like Qt has some sort of checking in the Open File dialog to detect when the user can't open the file. However if I specify it on the command line I can get it to crash as described.

![image](https://user-images.githubusercontent.com/3694843/218225804-f9ec3325-7319-491c-84f0-1c8a0e341390.png)

**Comment by dail8859** [comment]
The application will not crash now due to a null pointer. At some point in the future, I would like to add better user-facing error messages. As of right now it silently skips the file while logging a warning but not crashing is always a plus.
