### ISSUE TITLE
Unable to locate the program input point SystemParametersInfoForDpi in the dynamic link library

### ISSUE THREAD

**Issue by ahonggea** [dail8859/NotepadNext#323]
First of all, thanks to open source!But I have encountered some problems. It makes me unable to open and use your program normally.
# Error
os: window server 2012
version: v0.6
msg: Same as the title

**Comment by retanoj** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/6688779/218037610-4c64ea42-dfda-415e-8a70-687bd1f2d980.png">

same here.

**Comment by inkydragon** [comment]
> [qt.io/blog/qt6-development-hosts-and-targets](https://www.qt.io/blog/qt6-development-hosts-and-targets) - Windows 10 (and Windows 11) are supported by Qt6.
>
> ref: #322 

Does Qt version 5 work?

**Comment by dail8859** [comment]
As described in the documentation, only Windows 10 and later is supported. Your best option is to use Notepad++.

To be honestly I wasn't considering this when moving to Qt6, however due to the age of Windows 7 and 8, and some of the fixes Qt6 provides, I'm ok with this.

For anyone interested you should still be able to build Notepad Next with Qt5 but it won't be officially supported.
