### ISSUE TITLE
Interface language

### ISSUE THREAD

**Issue by YALdysse** [dail8859/NotepadNext#353]
Please, Add change interface language opportunity.
I can help you translate interface to ukrainian.

**Comment by dail8859** [comment]
Hi @YALdysse

The application does try to auto-detect your locale. You can find the documentation at the bottom of this document on how to translate it into your own language:

https://github.com/dail8859/NotepadNext/blob/master/doc/Translation.md#translation-process-for-translators

When you run Notepad Next, open the "Debug Log" under the help menu. Please post the first 10 lines or so because that shows the current locale it is trying to load.

**Comment by dail8859** [comment]
Thanks for the info. It's looking for `uk_UA` which doesn't exist yet since it has not been translated into that locale. 

If the application can auto detect your locale and load the translation if it exists, what's the need to change the language? Just to have the option to switch languages at runtime?

I'm not against the idea just want to make sure it best fits the need.

**Comment by YALdysse** [comment]
For example, I am ukrainian and I have installed english language os, but I want use ukrainian language in your program. In that case, do i have change OS language to have it ? It's not convenient.
Could you add .ts file for `uk_UA` locale, please ?

**Comment by dail8859** [comment]
@YALdysse 

I have added `i18n/NotepadNext_uk_UA.ts` to the repository.

You can use the [Qt Linguist](https://doc.qt.io/qt-6/linguist-translators.html) tool to translate the entries in the `ts` file. Once you have updated it, you can create a pull request with the updated `ts` file.

I have never done any of the translation for Notepad Next myself so I'm not sure how much help I can be if you run into issues, but still feel free to ask as there have been a few others around here that have contributed translations.

**Comment by YALdysse** [comment]
Thank you, very much.
