### ISSUE TITLE
[Feature request] Ability to "bookmark" lines

### ISSUE THREAD

**Issue by gloomytrousers** [dail8859/NotepadNext#364]
Ability to "bookmark" lines - e.g. highlight them with a coloured mark next to the line number. Ability to toggle on/off in various ways:
* via click on line number or keypress (e.g. Ctrl+F2 is common in other editors)
* via Find - bookmark matching lines
* invert all current bookmarks

As well as being useful visual cues, the bookmarks can be used for:
* Navigation - jump to next and previous bookmark, via keypress (e.g. F2 and Shift+F2) or menu item
* Replace only on bookmarked lines

**Comment by gloomytrousers** [comment]
Wow, thanks, that was quick!

**Comment by dail8859** [comment]
Closing for now since most of the features are implemented. The ones regarding find/replace functionality are definitely desireable but those will get rolled into a good revamp of the current Find/Replace dialog, since currently the code is a bit messy.

The commit adds several menu options:
![image](https://user-images.githubusercontent.com/3694843/231905050-5ea4f341-0bbb-4d44-aa84-63faee323cb4.png)
