### ISSUE TITLE
Incremental find / real-time regexp support

### ISSUE THREAD

**Issue by asvc** [dail8859/NotepadNext#4]
There was a lively discussion happening at https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8248 (also, see these feature proposals: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8278, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8247)

Would you be interesting in accepting this in NotepadNext?

Community discussion: https://community.notepad-plus-plus.org/topic/12722/survey-incremental-search-usefulness

**Comment by dail8859** [comment]
I think the functionality itself is a good idea (many other editors have this). The important part is making sure the UI is done correctly and cleanly. I'm not a fan of having a big clunky drop down menu like the example images had. Something more along the lines of Visual Studio, VS Code, Sublime, etc would be much cleaner.

**Comment by asvc** [comment]
Indeed! Would you like any help with the UX?

Ping @cmeriaux.

**Comment by dail8859** [comment]
Obviously I'm not a UX/UI designer so any help is appreciated.

My opinion is that between all the various editors that have this, countless hours have gone in to developing, refining, and using this kind of functionality in a text editor. All of them have come to a more-or-less similar design. So it is best to leverage all the past work done and start with something very similar to what the "industry standard" is.

**Comment by dail8859** [comment]
This is a very "proof of concept". The button's aren't working, they could use icons instead of text, had to do some other hackish things, but this is what I threw together very quickly.

![quickfind](https://user-images.githubusercontent.com/3694843/85925214-ed8e7c80-b864-11ea-9921-adbb5af550c4.gif)

**Comment by asvc** [comment]
Marvellous. Is there a way to test this build?

Re. buttons, perhaps let's start with the minimum number of common metaphors?

- <kbd>Aa</kbd> for the case-sensitive search.
- <kbd>.*</kbd> for the Regexp.
- ![image](https://user-images.githubusercontent.com/300146/85925773-e0f83b80-b8d9-11ea-8509-b6528b8fc250.png) for the "search in selection"

**Comment by dail8859** [comment]
I haven't pushed any code yet.

There are still some key problems with it currently...such as hacked together code, interfers with the smart highlighting, getting stuck on a single editor, no way for it to hide yet, etc.

Will try to address these obvious issues and then once I push the branch to Github, appveyor will have the build available.

**Comment by dail8859** [comment]
@asvc 

You can download a zip of these changes [here](https://ci.appveyor.com/project/dail8859/notepadnext/builds/33776408/artifacts).

Again there are _many_ things that are not working, or not working correctly.

**Comment by dail8859** [comment]
@asvc 

A new build should be available [here](https://ci.appveyor.com/project/dail8859/notepadnext/builds/33897871/artifacts). Now that this feature is merged into the dev branch I will consider this as an [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) and discussion of changes of behavior/appearance/etc can be opened as a new issue so that they can be individually discussed and defined. If you find an issue with the current behavior (crash, doesn't work under certain situations) feel free to post here.

A few known issues currently:
- Smart highlighting is broken since it shares an indicator with the quick find dialog
- Switching between docked areas can cause the dialog to show up in the wrong position (this is a problem in an upstream library I'm looking to address)
- At one point I was typing a regular expression and caused it to crash but not sure what the input was at the time

**Comment by dail8859** [comment]
Second bullet above has been fixed in the current dev branch.

**Comment by asvc** [comment]
Can't get it work. Here is what I have done:

1. Downloaded latest build from [AppVeyor](https://appveyorcidatav2.blob.core.windows.net/dail8859-85196/notepadnext/0-3-0-63/2iqdk0wfw1439yp7/NotepadNext-v0.3.0.63.zip)

2. Started NN

3. Copy-pasted bunch of text from this thread as can be seen on the screenshot below

![image](https://user-images.githubusercontent.com/300146/86523625-2acebc00-beae-11ea-82f8-dfbdb5654b01.png)

4. Clicked on the <kbd>.*</kbd>

5. Tried to enter <kbd>^</kbd> in the search field.

Application stopped responding and constantly consuming 80% of the single CPU core.

**Comment by dail8859** [comment]
Sounds like the 3rd bullet item listed above. I'm assuming it is due to zero length matches causing it to get stuck in an infinite loop. Will look into this.

**Comment by dail8859** [comment]
Fix will be available [here](https://ci.appveyor.com/project/dail8859/notepadnext/branch/dev/artifacts) on appveyor soon. Also fixed a bug in the regex engine.

**Comment by asvc** [comment]
Checked the build from AppVeyor - works with the caveat(s). For example, `\s` isn't recognized:

![image](https://user-images.githubusercontent.com/300146/86924502-b8403380-c16e-11ea-9854-fc15cc170d5f.png)

For the future - what is your preferred way to handle bug reports? New issue per bug / type of a bug / affected functionality / etc?

**Comment by dail8859** [comment]
Thanks for testing!

> For example, `\s` isn't recognized:

Is the `.*` option selected? (I don't have any way to test this myself current)

My guess is that this realtime regexp functionality will reveal problems in the regular expression engine. I'm too confident about the current implementation, so the whole regex engine might need addressed as well.

> what is your preferred way to handle bug reports?

I guess currently I don't have too much of a preference. Since this application is far from complete I don't see the need for alot of small individual bug reports, because usually if there is one bug, there are a few more similar bugs/updates that need addressed as well.

**Comment by dail8859** [comment]
Using ab55dafa7d07dcaff7e92e9de53eeaa22fb8ddeb the regex `\s\w` works for me.

![image](https://user-images.githubusercontent.com/3694843/86987658-89bd5b00-c164-11ea-89f4-6fddc087a2fe.png)

**Comment by dail8859** [comment]
Smart highlighter has been fixed.
