### ISSUE TITLE
Snap package ?

### ISSUE THREAD

**Issue by dev31337** [dail8859/NotepadNext#449]
Hi,

It is not an issue but a request, would it be possible to have a snap package ?

It would be easier to install on Ubuntu and your application is really a must have for old notepad++ users.

Regards.

**Comment by dail8859** [comment]
Though I'm familiar with Linux, I rarely use it anymore. I know there is already an AppImage and a Flatpak published for this application.

I'm not familiar enough to know what advantages a snap package would offer, and what kind of maintenance/overhead would be involved to support yet another distribution mechanism for Linux.

Anyone have thoughts about this?

**Comment by ZachBacon** [comment]
Flatpak is more widely used than snap, and while snaps are used. Ubuntu can install flatpaks and even if they don't, they can use appimages. But that's just my two pence.

**Comment by dev31337** [comment]
On Ubuntu the only solutions are to install Notepad++ snap package (which uses wine) or to install (no snap, through apt install) notepadqq (v2.0 beta) or notepad-- snap package.

Snap is the default packaging for Ubuntu, 

It would be nice to have a maintained snap package because NotepadNext is definately the best of the 3 others.

More information on how to build a snap package is available from here: https://snapcraft.io/build

**Comment by ZachBacon** [comment]
> On Ubuntu the only solutions are to install Notepad++ snap package (which uses wine) or to install notepadqq snap pakage  (for v1.4.8, or through apt-get install for v2.0 beta) or notepad-- snap package.
> 
> Snap is the default packaging for Ubuntu, 
> 
> It would be nice to have a maintained snap package because NotepadNext is definately the best of the 3 others.
> 
> More information on how to build a snap package is available from here: https://snapcraft.io/build

Or you could install the flatpak Deb package that IS in ubuntu's repositories and install the flatpak package that way. But that's just me giving advice, follow it or not. It's up to you. https://flatpak.org/setup/Ubuntu

**Comment by dev31337** [comment]
Personally I use the Appimage on Ubuntu so I'm good :)

My point was just to bring NotepadNext to all Ubuntu desktop users.

Canonical has decided to replace Flatpack by Snap on Ubuntu and their goal is to become the Linux store for all the distros, future will tell if they succeed....

**Comment by ZachBacon** [comment]
In my opinion, they failed. Most distro's that have supported snaps don't support the full capabilities of snap. IE confinement via apparmor for the kernel. To get those patches for the kernel usually have to wait a while for them to be rebased on a new kernel. And most distro's don't wait that long, hence the lack of confinement. Flatpak doesn't really require much to get it fully supported and doesn't require to patch a kernel.

**Comment by dev31337** [comment]
I agree, but to get back to the original point, Ubuntu being (as far as I know) the first desktop Linux distro, I think it is worth making a snap because all Ubuntu users are installing their application through the snap store application named "Ubuntu Software", this would bring NotepadNext to all the Ubuntu users doing a search on "Notepad" in the store.

**Comment by dail8859** [comment]
I'll still give it some thought. I'm not _completely_ opposed to it, but it would be yet another distribution mechanism to support, and yet another dimension to possible bugs. There's already bugs that are specific to AppImage or Flatpak and I'm not a native Linux user myself so I really can't offer any support for the Linux side of things...especially if the bugs are very distro or packaging specific.

**Comment by dev31337** [comment]
It is fine, as I told previously it works perfectly using your appimage :)

I would like to ask you a question on a different subject.

The most important feature for me is "Restore previous session" but when you enable it you get a strong warning.

Can you please tell me if this is really that dangerous to use ? is that an untested feature ? is that a recent feature ?

**Comment by dail8859** [comment]
> Can you please tell me if this is really that dangerous to use ? is that an untested feature ? is that a recent feature ?

I've been using it without issue and I'm assuming quite a few people have too since it was a very desired feature. It's kind of new but was tested pretty thoroughly. Really the only feedback I've gotten is #302 and that doesn't seem to point 100% to the application itself.

I guess the reason for the notice is that it has the **potential** to cause complete data loss and any unknown corner cases that be encountered on various systems.

**Comment by dail8859** [comment]
I'll close this for now as there doesn't seem to be a huge gain to deploy a snap package...maybe some day in the future.

> I think the message may be a little too strong since it seems to be quite safe :)

Under normal circumstances it works great, but there are so many unknown situations (network files, missing files, hard shutdown, system restart) that it very well could entirely lose data. At some point yes, I agree this message can be reworded or removed.

**Comment by popey** [comment]
Sorry to "necro" (as the cool kids say) this closed issue. 

I took the initiative to publish an (unofficial) snap of Notepad Next at https://snapcraft.io/notepadnext - I have clearly marked it unofficial, maintained by me. I have also linked to this repo, and your sponsor page. I am not trying to gain any credit or sponsorship revenue which should come to you.

I have some experience with this (I used to work on the Snap team at Canonical, but these days, I'm just an enthusiastic community contributor), with 30+ snaps I manage and many more I contribute to.

The Snap is a "classic" confined one, like most IDEs in the Snap Store. That means it's "unconfined", much like the AppImage or a traditional deb might be. So that shouldn't get in the way or cause user issues.

I understand you may want to manage only a portion of packaging systems (especially when Linux isn't your primary system), so I am happy to continue maintaining this on your behalf. Of course, in the future, if you'd instead take over or even 'collaborate' on the snap, I'll respectfully hand it over to you.

If you encounter any reported issues you think may be suspect due to the snap packaging, feel free to tag me on them. :pray: Thanks for making Notepad Next. It's rather remarkable.

**Comment by dail8859** [comment]
> I took the initiative to publish an (unofficial) snap of Notepad Next at https://snapcraft.io/notepadnext - I have clearly marked it unofficial, maintained by me.

This is definitely appreciated! And as long as someone isn't trying to pawn it off as their own then that's fine by me. 

> I understand you may want to manage only a portion of packaging systems (especially when Linux isn't your primary system), so I am happy to continue maintaining this on your behalf. Of course, in the future, if you'd instead take over or even 'collaborate' on the snap, I'll respectfully hand it over to you.

For now, I don't see any problem with it as-is. And I'm not opposed to 'officially' supporting it at some point, but so many people ask for different distribution methods but can't actually show what level of effort or automation there is vs the benefit. So, it is nice to see something actually working!

> If you encounter any reported issues you think may be suspect due to the snap packaging, feel free to tag me on them.

Will do!

My one ask, if possible is when building the application, to set the "DISTRIBUTION" variable to something like "Snap". Currently this is done to distinguish between the AppImages and Flatpack installs. For example the flatpak:

https://github.com/flathub/com.github.dail8859.NotepadNext/blob/7c44cc8cc09809b23263a05b7632f5a601318ddd/com.github.dail8859.NotepadNext.yml#L21

which uses qmake like this: `qmake PREFIX=/app src/NotepadNext.pro "DISTRIBUTION=Flatpak"`

If it is not possible that's fine, but this string will show up in the debug log which will probably help debug some stuff in the future.

**Comment by popey** [comment]
Awesome, thanks for the prompt response.

With regards to the debug log, the snap builds always have a file path which starts `/snap`, so for now, they're easy to spot:

```
[     0.479] I: =============================
[     0.479] I: Notepad Next v0.7
[     0.479] I: Build Date/Time: Apr 10 2024 10:01:46
[     0.479] I: Qt: 5.15.3
[     0.480] I: OS: Ubuntu 23.10
[     0.480] I: Locale: en_GB
[     0.480] I: CPU: x86_64
[     0.480] I: File Path: /snap/notepadnext/10/usr/bin/NotepadNext
[     0.480] I: Arguments: /snap/notepadnext/10/usr/bin/NotepadNext
[     0.480] I: =============================
```

However, it looks straightforward to add the `DISTRIBUTION` setting, so I'll add that right away.

**Comment by popey** [comment]
Ok, this works. The next build will have the distribution.

```
[     0.313] I: =============================
[     0.313] I: Notepad Next v0.7 (Snap)
[     0.313] I: Build Date/Time: Apr 11 2024 10:06:39
[     0.313] I: Qt: 5.15.3
[     0.313] I: OS: Ubuntu 23.10
[     0.313] I: Locale: en_GB
[     0.313] I: CPU: x86_64
[     0.313] I: File Path: /snap/notepadnext/x1/usr/bin/NotepadNext
[     0.313] I: Arguments: /snap/notepadnext/x1/usr/bin/NotepadNext
[     0.313] I: =============================
```

**Comment by dail8859** [comment]
> Ok, this works. The next build will have the distribution.

@popey Awesome! Thanks!

**Comment by dail8859** [comment]
@popey Also, is there a specific reason it is using Qt5.15?

My plan is to maintain 5.15 support as long it is feasible, but it may be dropped eventually. I know the flatpak is still using it but eventually would like to get everything to Qt6.5+

**Comment by popey** [comment]
Good question.

It builds inside a container running Ubuntu 22.04 LTS, on account of the metadata specifying `base: core22`. So during the build it has access to whatever packages are in the Ubuntu 22.04 repos. They tend to get bug and security fixes, but not whole release updates within the lifetime of the Ubuntu release.

There will be a core24 coming soon (April or beyond) on which we could build, and that would have whatever is in the Ubuntu 24.04 LTS repo. It looks like 24.04 will ship with qmake6 6.4.2, so even then, not Qt5+

The alternatives are a bit brutal, from my side, but not your problem :) 

We can leverage a repository that someone else maintains which contains more modern Qt builds. Alternatively, the most brutal, is to build all the Qt toolchain and required libraries from scratch, every time the snap builds. Another, other option, is to split out Qt toolchain and dependencies into a separate "content" snap which the notepadnext snap could leverage.

I know, for example the telegram-desktop messaging snap builds Qt when it builds telegram, as a result the snap (for a desktop messaging app) is enormous, at 421MB. They build a patched Qt5 though, not 6.

What sort of timeline are you thinking?

I am sure you're not alone, others will want to move to more modern Qt at some point, it's just who does it first, and who does it second, and gets to copy & paste the config rather than iterate themselves :D

**Comment by dail8859** [comment]
> What sort of timeline are you thinking?

No set timeline. Binaries for Windows, MacOS, and Linux AppImage are all Qt6.5. Linux Flatpak is Qt5.15. My only worry is trying to support multiple Qt versions that are growing further and further part over time.

Currently it hasn't been bad to maintain 5.15 support, but at some point, either 3rd party libraries might drop support, or there might be more breaking changes to the Qt API, Qt version-specific bugs, etc.

**Comment by popey** [comment]
Ok, if it works in the AppImage, then I suspect I can crowbar Qt6 into the snap too. Leave it with me, and I'll have a play and see if I can make a working Qt6-based NotepadNext snap.

**Comment by dail8859** [comment]
We kind of left it as "just stick with Qt5.15 for now" for flatpak:

https://github.com/flathub/com.github.dail8859.NotepadNext/pull/12#issuecomment-1410972944

But given how long ago that was, I'd guess Qt6+ would work better now.

If you can get Qt6 working without too much blood/sweat/tears then that's fine, but since there is no _real_ reason yet to drop it then Qt5.15 is fine for the time being.
