### ISSUE TITLE
W: QTextCursor::setPosition: Position 'xxxxx' out of range

### ISSUE THREAD

**Issue by UdeRecife** [dail8859/NotepadNext#484]
**OS**: Arch Linux (updated).
**UI**: KDE Plasma: 5.27.9
      QT 5.15.11
**Version**: notepadnext 0.6.4-1

**Problem**:
open NotepadNext. Try to move the window and the whole system UI freezes. When I kill it on another TTY, I see the following message repeated ad infinitum:

`W: QTextCursor::setPosition: Position '72000' out of range`

**Comment by dail8859** [comment]
Thanks for the report. I'm strictly a Windows user so I haven't seen anything like that before.

If the application worked at one time you can launch it with the `--reset-settings` flag to remove all application settings if you are willing to lose any configuration (not that there is much to configure yet).

Other than that maybe someone else will be able to debug it for Linux. My only guess is that it _may_ be the "Debug Log" window since that uses a Qt text box control and appends text to it.

**Comment by dail8859** [comment]
Notepad Next doesn't call `setPosition()` directly at all so I guess it is either a Qt bug or something with KDE.
