### ISSUE TITLE
Crash on startup C: SingleApplication: Unable to attach to shared memory block.

### ISSUE THREAD

**Issue by cedric-airsupplies** [dail8859/NotepadNext#493]
I've made and installed this package on arch linux:
https://aur.archlinux.org/packages/notepadnext

When I start the package, I get this error:
```
$ NotepadNext 
[     0.062] C: SingleApplication: Unable to attach to shared memory block.
[     0.062] C: SingleApplication:  QSharedMemory::AlreadyExists "QSharedMemory::create: already exists"
```
versions:
```
$ uname -a
Linux cedric 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux
$ pacman  -Q notepadnext
notepadnext 0.6.4-1

```

**Comment by dail8859** [comment]
I do not maintain that package at all. I've not seen that error before or had anyone else report it.

Your best option is to contact the maintainer of that package or you can report the issue here https://github.com/itay-grudev/SingleApplication which is the 3rd party library that Notepad Next uses.
