### ISSUE TITLE
Allow bookmarks to be persistent

### ISSUE THREAD

**Issue by cschuber** [dail8859/NotepadNext#503]
Notepad++ bookmarks are persistent across app restarts. Having recently installed NotepadNext on a FreeBSD laptop, I use it to keep track of an MIT Kerberos project I'm working on (importing into FreeBSD). Unfortunately the bookmarks I used to keep track of my progress (a todo list + notes) were gone when I restarted the NotepadNext and reloaded previously open notepads. This was unexpected since I use Notepad++ at $JOB for the same purpose, keeping track of my work.

I'm not sure where Notepad++ keeps track of its bookmarks -- probably the registry. NotepadNext could maintain bookmark state in a file or subdirectory in ~/.config. Bookmark state could be as simple as a list of line numbers.

State could be lost if someone, for example, edits a file with another editor. But that could be easily determined by inspecting the mtime of the file and the mtime of the bookmark file (or one could keep a timestamp in a single large file if you choose to implement it that way). If the file has a newer timestamp than the bookmark state information, simply discard the bookmarks.

**Comment by dail8859** [comment]
Thanks for the suggestion.

> I'm not sure where Notepad++ keeps track of its bookmarks -- probably the registry

It keeps it in the session.xml file that stores other details about which files were opened, where the cursor was, etc.

> State could be lost if someone, for example, edits a file with another editor. But that could be easily determined by inspecting the mtime of the file and the mtime of the bookmark file

In theory just because something is edited doesn't mean the bookmarks are invalid. I quickly glanced through the Notepad++ source and it doesn't do any kinds of checks like this, but I do agree the bookmarks could potentially be wrong if externally edited. I don't recall having anyone complain about it, but that's something that could be adjusted later.

In theory this feature shouldn't be too hard to implement. Like you said just store a list of line numbers and re-marking those lines on startup.

**Comment by cschuber** [comment]
Thank you. I will create a notepadnext-devel FreeBSD port/pkg to track your development branch. This will allow users to have this new feature before the next release.
