### ISSUE TITLE
[Feature request] Find index match count

### ISSUE THREAD

**Issue by Crunchbits** [dail8859/NotepadNext#546]
Text in the Quick Find and potentially the Find Window that shows the index match count. That is to say it will show both the total matches and the current match number.

For example, it may show up as something like "3 of 9 matches" or "Found next match [3/9]".

Also potentially have a setting to only enable this feature for text files under custom set number of lines/characters (assuming this would help prevent slow down on big files).

**Comment by dail8859** [comment]
Definitely a good idea. I use this kind of feature alot when searching in a web browser :)

> Also potentially have a setting to only enable this feature for text files under custom set number of lines/characters (assuming this would help prevent slow down on big files).

Yeah this is the key part of it -- because at a minimum it will have to search the entire document once to get an index and total count. As long as it is not edited then the total count and index could be cached.
