### ISSUE TITLE
Can you add simplified Chinese language

### ISSUE THREAD

**Issue by HeliusHao** [dail8859/NotepadNext#56]
Can you add simplified Chinese language，thank

**Comment by dail8859** [comment]
Hi @HeliusHao, thanks for opening this issue.

I'd be interested in working to get the application translated, however English is my only language plus I just don't know enough about the Qt translation system. 

If someone is interested in helping to lead this work to address some of the technical issues and the general process of translating the application, I'd be willing to help where possible.

**Comment by lanmanck** [comment]
language can be added through community, I think.

**Comment by mandyedi** [comment]
Hi @dail8859,
I'd like to work on adding the translation to NotepadNext, it seems quite an interesting task. I need to look up the technical background though, but meanwhile, I can add some UI for settings. I guess the change language menu should be in the preferences. I honestly don't know where it is in the original version, because I always used the English version.

**Comment by dail8859** [comment]
Hi @mandyedi 

I think https://doc.qt.io/qt-5/internationalization.html would be the best place to start. 

> I can add some UI for settings

I don't believe that would be required to start with. Especially because I plan on changing the preferences dialog alot at some point. So if you do look at this don't put too much effort into making it look pretty.

The difficult part will be ensuring the translation is working and knowing how to do it. There's a snippet of code on that documentation that gets the user's Locale and attempts to load the appropriate translation if it exists.

**Comment by mandyedi** [comment]
The translation process actually quite simple, but it might need some work to set up.
This is a very rough description of the main steps:
1. The strings meant for translation are marked using tr() in source code.
2. lupdate - A tool that scans the source files for tr() and places the strings in a .ts xml file.
3. A translator provides translations by opening the .ts file using Qt Linguist.
4. lrelease - A tool that takes the .ts which contains translated strings and converts them into a binary .qm format that can be loaded into an application at runtime.

I can write a detailed manual for developers and translators and add it to the docs folder.

**Comment by dail8859** [comment]
That's good to hear. When I glanced at that documentation a while ago it seems to be pretty good about explaining everything, I just didn't have a need to go through it in detail at the time.

> I can write a detailed manual for developers and translators and add it to the docs folder.

Yeah that would be good. I don't think it needs to be overly detailed especially if the Qt documentation does a good job. But a list of steps would be good.

**Comment by dail8859** [comment]
I fumbled through part of the process. No guarantee these translations are correct, but more just a test to see if it can load translations:

![image](https://user-images.githubusercontent.com/3694843/163588334-d98f79d4-e251-4ab2-a129-4840ddf7e2bd.png)
