### ISSUE TITLE
Feature request: word count in statusbar, insert key -> overwrite

### ISSUE THREAD

**Issue by nordwin82** [dail8859/NotepadNext#582]
### Description

Really love what you are doing.

Feature request: word count in statusbar, insert key switches between insert and overwrite

**Comment by dail8859** [comment]
Just curious, what is the exact need for having a live, updated wordcount in a status bar?

**Comment by nordwin82** [comment]
Hi, word count would be useful when you have an obligation to write a text of a certain word count. A few times a year I write 300 words for a local dutch publication. Maybe I am the only one with such tasks ;-)

**Comment by dail8859** [comment]
I did add overtyping in the next release.

---

Having a real-time word count is a very small use case for the tradeoff of performance (i.e. rescanning the document every time an edit is made). Also the definition of 'what is a word' can vary between users which adds more complexity.

I'd recommend sticking to word processing applications that need more 'word' based functionality rather than a text editor.
