### ISSUE TITLE
default highlight for .log files

### ISSUE THREAD

**Issue by wjx0912** [dail8859/NotepadNext#592]
### Description

![Snipaste_2024-07-05_14-05-54](https://github.com/dail8859/NotepadNext/assets/5556482/6e0f218a-516f-48d1-9a66-4216b9c328b7)

This is a very common example, using notepad- it looks beautiful, can notepad next do this by default too.

thanks

**Comment by dail8859** [comment]
I do not know how notepad-- does this so I can't say for sure. If it is a normal built in Lexilla lexer then yes. But if notepad-- did some sort of custom implementation then it probably isn't easily ported over.

I'll close this for now since I am assuming this is a custom implementation but if it is a built in lexer then that should be easy enough.
