### ISSUE TITLE
Can't compile in MacOS Intel.

### ISSUE THREAD

**Issue by filipemd** [dail8859/NotepadNext#593]
### Operating System and Version

MacOS Sonoma x86_64

### Distribution

dmg

### Description

When I compile, gives this error:

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [NotepadNext.app/Contents/MacOS/NotepadNext] Error 1
make: *** [sub-NotepadNext-make_first] Error 2

### Steps to Reproduce

1. Use MacOS Sonoma Intel;
2. Copy the source code;
3. Compile using `qmake`.

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment]
I don't use a Mac so I cannot say for certain what is wrong. You also gave very general steps rather than specifics of what you are running. Not sure if the commands ran themselves are incorrect, or a system configuration issue, or something in the qmake files needs updated.

You can look at the workflow which includes steps to build it on MacOS which might help possibly: https://github.com/dail8859/NotepadNext/blob/84a861b60ea39914724ee1ab7e9f9d4a256b84e1/.github/workflows/build.yml
