### ISSUE TITLE
"Delete all macros" Button in Macros Editor window

### ISSUE THREAD

**Issue by YALdysse** [dail8859/NotepadNext#611]
### Description

![deleteAllMacros_NotepadNext](https://github.com/user-attachments/assets/9a9bc885-b0d4-4255-8ca0-eb94540a968b)

If you have saved a lot of macros (as shown in the screenshot) and need to delete them all, you will have to delete them one by one. This is inconvenient and time-consuming. Therefore, I suggest adding a button to the macro editor that will delete all existing macros.  I have shown the place where it can be located on the screenshot.

**Comment by dail8859** [comment]
Thanks for the suggestion. However, I think for now it is safer to not add a delete all button. It would not be common for someone to want to delete all their macros. It would also likely lead to a user mis-clicking and accidentally agreeing to delete all their macros (because we all know users don't always read warning messages 😄). Even so, to delete all the macros still only takes a few seconds. Just put the mouse on the delete button the repeatedly press `Click` then `Enter`.
