### ISSUE TITLE
Button pop-up is too light

### ISSUE THREAD

**Issue by Xeknos** [dail8859/NotepadNext#627]
### Operating System and Version

Linux Mint 22

### Distribution

Flathub

### Description

Mouse-over pop-ups on menu bar buttons are way too light, and barely readable. I actually thought they were empty until I looked more closely. See attached screenshot.

### Steps to Reproduce

1. Open Notepad Next.
2. Mouse over one of the buttons on the menu bar.

### Additional Details

![Notpad next pop up error](https://github.com/user-attachments/assets/628a5412-20d1-4080-ba29-37faab756a95)

**Comment by dail8859** [comment]
This problem is due to the whatever is overriding the style (the dark background, etc) since that is not part of this application.

There have been other cases of this type of thing, so I've added in a feature to allow tweaking the applicating styling. Next to your `NotepadNext.ini` file (that varies depending on your system) you can create a `custom.css` file to apply additional styling using [Qt Style Sheets](https://doc.qt.io/qt-6/stylesheet-reference.html) to the application. In your case you can use:

```css
QToolTip { color: black; }
```
