### ISSUE TITLE
Auto adjust length of horizontal scroll bar

### ISSUE THREAD

**Issue by yihuajack** [dail8859/NotepadNext#659]
### Description

If users paste a very long line to the editor, the horizontal scroll bar is very long. However, if users break the line into many separate lines until each line is shorter than the size of the editor window, the length of the horizontal scroll bar does not change.

### Describe the solution you'd like

When the longest line changes, the horizontal scroll bar should change consistently.

**Comment by dail8859** [comment]
The underlying Scintilla library is what handles all the lower-level text editing. Their "scroll width tracking" specifically [states](https://scintilla.org/ScintillaDoc.html#SCI_SETSCROLLWIDTHTRACKING):

> If scroll width tracking is enabled then the scroll width is adjusted to ensure that all of the lines currently displayed can be completely scrolled. This mode never adjusts the scroll width to be narrower.

I'm not 100% sure the rationale behind this but is likely due to performance issues. The Scintilla library would have to support this functionality for Notepad Next to utilize it.
