### ISSUE TITLE
Listed as end of life

### ISSUE THREAD

**Issue by Vintercon** [dail8859/NotepadNext#682]
### Operating System and Version

Pop_OS

### Distribution

Pop_shop

### Description

Notepad Next is marked End of life but has the Nov update. Not really a bug, thou it did intially steer me away from using the Pop_Shop version.

### Steps to Reproduce

1. On a machine with pop_os, open Pop_shop
2. Search for notepad next

### Additional Details

e.g. screenshots, logs, etc
![image](https://github.com/user-attachments/assets/129ba94d-e528-4939-9821-9cfd56c5a5bb)

**Comment by dail8859** [comment]
Thanks for opening this.

I don't manage the app in the Pop Shop so I cannot say specifically.

My guess would be that since it still uses Qt 6.5 it is saying it is end of life. There are 3rd party libraries this application depends on that aren't working above 6.5 so for now the application needs to stay with an older version. Also see #584
