### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by abb128** [dail8859/NotepadNext#84]
Flatpak offers some advantages over AppImage, namely automatic updates, more trustworthy distribution and sandboxing. It'd be nice to have a Flatpak package for those who prefer Flatpak.

**Comment by zocker-160** [comment]
I am not the developer, but if there is interest, I would be willing to create the Flatpak.

**Comment by zocker-160** [comment]
I managed to create a working flatpak, if anyone wants to give it a try:
[NotepadNext.zip](https://github.com/dail8859/NotepadNext/files/8465343/NotepadNext.zip)

so if @dail8859 is interested, we could push this to Flathub.

**Comment by zocker-160** [comment]
@dail8859 let me answer your questions:

1. all flatpaks will be built on Flahub.org's servers fully automated once it is accepted (nothing needs to be done on your end in terms of building)
2. once the package is accepted, the submitter gets access to a repository which he can push directly to
see: https://github.com/flathub/flathub/wiki/App-Maintenance
and: https://github.com/flathub/flathub/wiki/App-Submission
3. it will be hosted on Flathub.org which has public built in statistics: 
see for example: https://beta.flathub.org/en/apps/details/org.mozilla.firefox

What I created above is a local Flatpak, which is meant for testing and it is not the "normal" way of distributing it.

> For now, I want to be very cautious what and how many release streams are supported because it can quickly get burdensome

I would recommend you to focus on Flatpak and Flatpak only, because it supports _all_ Linux distributions out there (unlike Appimage), it gives you great exposure to your application because all major distributions have flatpak support in the build in software store, so any user just needs to search for your application, presses install and done.

**Comment by dail8859** [comment]
@zocker-160

Ah OK that makes **much** more sense now! I'm not overly set on sticking with AppImage, it was just easy and convenient to start with since I was looking for some way to get it deployed for Linux. I can definitely see some good advantages with flatpak (e.g. exposure and auto updates).

I'll need to do some more investigation with flatpak to see what all it entails. It seems you may have something semi-functional already.

**Comment by dail8859** [comment]
@zocker-160 

v0.5 (bd6ca110d8219bde7467866e0d67da53353c69c8) has been released now.

**Comment by zocker-160** [comment]
@dail8859 I just created the submission request to Flathub: https://github.com/flathub/flathub/pull/3024

**Comment by zocker-160** [comment]
:tada: Notepad Next is now on flathub: https://flathub.org/apps/details/com.github.dail8859.NotepadNext :tada: 

cc @dail8859 @abb128

**Comment by dail8859** [comment]
@zocker-160 Awesome 🎉 Thanks for all the work you've put into this!

I see the application version on FlatHub shows `v0.4.9` I'm assuming that was a side effect of not having the metainfo updated at time of release?

**Comment by zocker-160** [comment]
> I see the application version on FlatHub shows v0.4.9 I'm assuming that was a side effect of not having the metainfo updated at time of release?

@dail8859 yes exactly. it actually installs v0.5, but it shows as v0.4.9 because that is what the metainfo is telling flathub,
Also there are a few small issues with the mimetypes, I will create PR shortly.

**Comment by dail8859** [comment]
So as far as this specific issue is concerned is it ok to close now?

**Comment by zocker-160** [comment]
yes I think you can close it.

**Comment by zocker-160** [comment]
@dail8859 you almost reached 1,200 downloads on Flathub after 12 days, does not seem too bad xD
https://beta.flathub.org/apps/details/com.github.dail8859.NotepadNext

**Comment by dail8859** [comment]
@zocker-160 Not bad at all!
